---
- name: Remove all (non default) gems
  script: ruby_cleanup.sh
  register: rubycleanupout
  ignore_errors: true
  changed_when: "'Clean up complete' in rubycleanupout.stdout"

- name: Install gem packages
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    executable: "$HOME/.rbenv/shims/gem"
    user_install: false
  with_items:
    - "{{ gem_packages }}"

# GEMs: Cocoapods
- name: pod setup
  shell: bash -l -c "pod setup || pod setup"
  when: is_incremental_setup|default(false) == false

- name: CocoaPods specs install with pod
  shell: bash -l -c "pod repo add master https://github.com/CocoaPods/Specs.git || pod repo update master"
  when: is_incremental_setup|default(false) == false and not lookup('env', 'IS_CI')

# The pod repo add just clone the repository.
# Cocopods master is huge, and we need the HEAD only so we clone that during CI run.
- name: CocoaPods specs install with git
  shell: bash -l -c "git clone --depth=1 https://github.com/CocoaPods/Specs.git ~/.cocoapods/repos/master ||  git -C ~/.cocoapods/repos/master pull --ff-only --depth=1"
  when: is_incremental_setup|default(false) == false and lookup('env', 'IS_CI')
