---
- name: is xcodebuild available
  command: xcodebuild -version
  register: xcodebuild_version

- name: xcodebuild version is unexpected
  fail:
    msg: xcodebuild version is unexpected
  when: xcode_numeric_version not in xcodebuild_version.stdout

- name: Check if directories exist
  include: "dir_check.yml path={{ item }}"
  with_items:
    - /Applications/Xcode.app
    - /Library/Developer/CommandLineTools
