---
- name: "check if {{ path }} exists"
  stat:
    path: "{{ path }}"
  register: dir_exists

- name: "{{ path }} doesn't exist"
  fail:
    msg: "{{ path }} doesn't exist"
  when: >
        not
          (dir_exists.stat.exists
        and
          (dir_exists.stat.isdir or dir_exists.stat.islnk))
