---
simulators:
  - 'watchOS 6.1'
  - 'watchOS 6.0'
  - 'tvOS 13.3'
  - 'tvOS 13.2'
  - 'tvOS 13.0'
  - 'iOS 13.3'
  - 'iOS 13.2'
  - 'iOS 13.1'
  - 'iOS 13.0'
  - 'iOS 12.4'
  - 'iOS 12.2'
  - 'iOS 12.1'
  - 'iOS 12.0'
