---
- name: load distribution specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
      - '{{ ansible_os_family }}.yml'
      - default.yml

- name: ensure .ssh folder is ok
  become: true
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    owner: "{{ param_user }}"
    mode: "0700"

- name: Generate all absent ssh host keys
  become: true
  shell: ssh-keygen -A

# Disable every non SSH key based setup option
# allow only SSH key based SSH login
- name: sshd_config settings
  become: true
  template:
    src: templates/etc/ssh/sshd_config.j2
    dest: "/etc/ssh/sshd_config"
    owner: root
    mode: "0644"
    validate: '/usr/sbin/sshd -t -f %s'
    backup: true

- name: ssh connection config (user specific)
  copy:
    src: files/ssh-config
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    owner: "{{ param_user }}"
    group: "{{ param_group }}"
    mode: "0600"
