FROM linuxbrew/linuxbrew
USER root
# Create `ansible` user with sudo permissions and membership in `DEPLOY_GROUP`
ENV ANSIBLE_USER=ansible SUDO_GROUP=linuxbrew DEPLOY_GROUP=deployer
RUN set -xe \
  && groupadd -r ${ANSIBLE_USER} \
  && groupadd -r ${DEPLOY_GROUP} \
  && useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} \
  && usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} \
  && usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} \
  && sed -i "/^%${SUDO_GROUP}/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers
# Install developer tools
ENV PATH="${PATH}:/home/linuxbrew/.rbenv/versions/2.6.5/bin/:/home/linuxbrew/.rbenv/shims/"
RUN sudo apt-get update && \
    sudo apt-get install -y \
    libssl-dev \
    make \
    cmake \
    gcc \
    git \
    libcurl4-openssl-dev \
    openjdk-8-jdk \
    unzip \
    openssh-server \
    && mkdir /var/run/sshd

USER linuxbrew
