---
- name: Make sure xcversion / xcode-install is installed
  gem:
    name: xcode-install
    user_install: false
    executable: "{{ ansible_env.HOME }}/.rbenv/shims/gem"

- name: Test Simulator installed - {{ item }}
  shell: bash -l -c "xcversion simulators | grep '(installed)' | grep '{{ item }}'"
  register: simulator_installed
  changed_when: false
  ignore_errors: true

- name: Install xcode simulators - {{ item }}
  shell: bash -l -c "xcversion simulators --install='{{ item }}'"
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"
    FASTLANE_SESSION: "{{ FASTLANE_SESSION | b64decode }}"
  when: simulator_installed.rc == 1
