export DOTBASHRC_LOADED=1
export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

# Homebrew
#  Don't do auto update
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ANALYTICS=1

# Go
export PATH="$PATH:/usr/local/opt/go/libexec/bin"
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"

# Bitrise environments
[[ -s "$HOME/.profiles/bitrise_profile" ]] && source "$HOME/.profiles/bitrise_profile"

# Xamarin environments, if exists
[[ -s "$HOME/.profiles/xamarin_profile" ]] && source "$HOME/.profiles/xamarin_profile"

# keep a newline at the end of this file
