---
- name: "Azul JDK: download Java 8"
  get_url:
    url: https://cdn.azul.com/zulu/bin/zulu18.0.57-ea-jdk18.0.0-ea.24-macosx_aarch64.zip
    dest: /tmp/azul-jdk-8.zip

- name: "Java 8 binary: install"
  unarchive:
    src: /tmp/azul-jdk-8.zip
    dest: /usr/java_home/1.8
    owner: "{{ param_user }}"
    copy: false
    mode: 0700
  become: true

- name: "Azul JDK: remove temp file"
  file:
    path: /tmp/azul-jdk-8.zip
    state: absent

- name: "Azul JDK: download Java 11"
  get_url:
    url: https://cdn.azul.com/zulu/bin/zulu11.52.13-ca-jdk11.0.13-macosx_aarch64.zip
    dest: /tmp/azul-jdk-11.zip

- name: "Java 11 binary: install"
  unarchive:
    src: /tmp/azul-jdk-11.zip
    dest: /usr/java_home/11
    owner: "{{ param_user }}"
    copy: false
    mode: 0700
  become: true

- name: "Azul JDK: remove temp file"
  file:
    path: /tmp/azul-jdk-11.zip
    state: absent
