---
- name: Install go
  homebrew:
    name: go@1.16
    state: present
    update_homebrew: true

- name: Test if there is a latest go installed
  shell: bash -l -c "brew list | grep -x go"
  changed_when: false
  ignore_errors: true
  register: latest_is_installed

- name: unlink latest go
  shell: bash -l -c "brew unlink go"
  when: latest_is_installed.rc == 0

- name: Link go 1.16
  shell: bash -l -c "brew link go@1.16"

- name: prepare GOPATH dirs
  file:
    path: "{{ ansible_env.HOME }}/go/{{ item.fold_path }}"
    state: directory
    owner: "{{ param_user }}"
  with_items:
    - { fold_path: 'src' }
    - { fold_path: 'bin' }
    - { fold_path: 'pkg' }

- name: Set up GO111MODULE
  shell: bash -l -c "go env -w GO111MODULE=auto"
...
