---
# Setup Bitrise specific folders:
# Setup the base folders / paths, referenced by ~/.profiles/bitrise_profile
# These folders will be created in the HOME directory.
- name: Setup Bitrise specific folders
  file:
    path: "{{ bitrise_specific_folder_path }}"
    state: directory
    owner: "{{ param_user }}"
  with_items:
    - "{{ bitrise_specific_folders }}"
