---
- name: Install ruby versions
  shell: bash -l -c "rbenv install --skip-existing {{ item.version }}"
  when: is_incremental_setup|default(false) == false
  with_items:
    - "{{ default_ruby }}"
    - "{{ ruby_versions }}"

- name: Set ruby latest to global
  shell: bash -l -c "rbenv global {{ item.version }}"
  when: is_incremental_setup|default(false) == false
  with_items:
    - "{{ default_ruby }}"

- name: Install gem packages
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    executable: "$HOME/.rbenv/shims/gem"
    user_install: false
  with_items:
    - "{{ gem_packages }}"

# GEMs: Cocoapods
- name: pod setup
  shell: bash -l -c "pod setup || pod setup"
  when: is_incremental_setup|default(false) == false

- name: CocoaPods specs install with pod
  shell: bash -l -c "pod repo add master https://github.com/CocoaPods/Specs.git"
  when: is_incremental_setup|default(false) == false and not lookup('env', 'IS_CI')

# The pod repo add just clone the repository.
# Cocopods master is huge, and we need the HEAD only so we clone that during CI run.
- name: CocoaPods specs install with git
  shell: bash -l -c "git clone --depth=1 https://github.com/CocoaPods/Specs.git ~/.cocoapods/repos/master"
  when: is_incremental_setup|default(false) == false and lookup('env', 'IS_CI')
